version: 2
jobs:
  build:
    working_directory: ~/hiper_stub
    docker:
      - image: circleci/ruby:2.5.8-node
        environment:
          PGHOST: localhost
          PGUSER: hiper
          RAILS_ENV: test
          BUNDLER_VERSION: 2.1.2
      - image: circleci/postgres:9.5.21
        environment:
          POSTGRES_USER: hiper
          POSTGRES_DB: hiper_stub_test
          POSTGRES_PASSWORD: password
      - image: redis:latest
    steps:
      # Special step to checkout repository
      - checkout

      - run:
          name: create database.yml
          command: mv config/database.ci.yml config/database.yml

      - run:
          name: create secrets.yml
          command: mv config/secrets.ci.yml config/secrets.yml

      - run:
          name: Install Bundler 2.0+
          command: gem update bundler

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - rails-net200601-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-net200601-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      - save_cache:
          key: rails-net200601-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bundle exec rake db:create db:migrate

      - run:
          name: Rubocop linter
          command: bundle exec rubocop --lint

      - run:
          name: Rspec
          command: bundle exec rspec --format documentation --format RspecJunitFormatter -o ~/rspec/rspec.xml

      - run:
          name: Brakeman
          command: bundle exec brakeman

      - store_test_results:
          path: ~/rspec
