default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  host: localhost
  port: 5432
  database: xsell_dev
  username: c_aksharma
  password: Akki@123456

test:
  <<: *default
  host: localhost
  port: 5432
  database: xsell_test
  username: c_aksharma
  password: Akki@123456